core/urls.py
from django.urls import path

from core.views import (
    HomeView,
    RegistrationView,
    LoginUserView,
    LogoutUserView,
    ProductListView,
    ProductAddView,
    ProductEditView,
    PurchaseListView,
    RefundsListView,
    ProductPurchaseView,
    PurchaseRefundView,
    RefundsAcceptView,
    RefundsDeclineView,
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('register/', RegistrationView.as_view(), name='register'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('products/', ProductListView.as_view(), name='products'),
    path('products/new/', ProductAddView.as_view(), name='product_add'),
    path('products/<int:pk>/edit/', ProductEditView.as_view(), name='product_edit'),
    path('products/purchase/', ProductPurchaseView.as_view(), name='product_purchase'),
    path('purchases/', PurchaseListView.as_view(), name='purchases'),
    path('purchases/refund', PurchaseRefundView.as_view(), name='purchase_refund'),
    path('refunds/', RefundsListView.as_view(), name='refunds'),
    path('refunds/accept/<int:pk>', RefundsAcceptView.as_view(), name='refunds_accept'),
    path('refunds/decline/<int:pk>', RefundsDeclineView.as_view(), name='refunds_decline'),
]

web_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.utils import timezone


class User(AbstractUser):
    wallet = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

    def __str__(self):
        return self.username


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=7, decimal_places=2)
    # image = models.ImageField()
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return self.name


class Purchase(models.Model):
    quantity = models.PositiveIntegerField()
    purchased_at = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='purchases')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='purchases')

    def __str__(self):
        return f'{self.quantity} pcs. of {self.product.name.upper()} purchased by {self.user.username.upper()} ' \
               f'at {self.purchased_at}'


class Refund(models.Model):
    request_datetime = models.DateTimeField(auto_now_add=True)
    purchase = models.OneToOneField(Purchase, on_delete=models.CASCADE, related_name='refund')

    def __str__(self):
        return f'{self.purchase.quantity} pcs. of {self.purchase.product.name.upper()} purchased ' \
               f'by {self.purchase.user.username.upper()}'

core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from core.models import User, Purchase, Refund


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=False)

    class Meta:
        model = User
        fields = ['username']
        widgets = {
            'email': forms.EmailInput(),
            'password': forms.PasswordInput(),
        }


class PurchaseForm(forms.ModelForm):
    quantity = forms.IntegerField(min_value=1)

    class Meta:
        model = Purchase
        fields = ['quantity']


class RefundForm(forms.ModelForm):
    class Meta:
        model = Refund
        fields = []

core/views.py
from datetime import timedelta

from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.mixins import AccessMixin, LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import FormView, UpdateView, CreateView, DeleteView
from django.urls import reverse, reverse_lazy

from core.forms import RegistrationForm, PurchaseForm, RefundForm
from core.models import Product, Purchase, User, Refund


class SuperuserRequiredMixin(UserPassesTestMixin, AccessMixin):
    login_url = 'core:home'

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        return HttpResponseRedirect(reverse(self.login_url))


class HomeView(TemplateView):
    template_name = 'home.html'


class RegistrationView(FormView):
    form_class = RegistrationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('core:home')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.wallet = 10000
        user.save()
        login(self.request, user)
        return super().form_valid(form)


class LoginUserView(LoginView):
    template_name = 'registration/login.html'

    def get_success_url(self):
        return reverse_lazy('core:home')


class LogoutUserView(LogoutView):
    template_name = 'registration/logout.html'

    def get_success_url(self):
        return reverse_lazy('core:home')


class ProductAddView(SuperuserRequiredMixin, CreateView):
    template_name = 'product_add.html'
    model = Product
    fields = ['name', 'description', 'price', 'quantity']
    success_url = reverse_lazy('core:products')


class ProductPurchaseView(LoginRequiredMixin, CreateView):
    login_url = 'login'
    form_class = PurchaseForm
    success_url = reverse_lazy('core:products')

    def form_valid(self, form):
        product_pk = self.request.POST.get('product_pk')
        product = Product.objects.get(id=product_pk)
        quantity = int(self.request.POST.get('quantity'))
        user = self.request.user
        page_number = self.request.GET.get('page')

        flag = True
        if product.price * quantity > user.wallet:
            messages.error(self.request, "Not enough cash")
            flag = False

        if product.quantity < quantity:
            messages.error(self.request, "Not enough products")
            flag = False

        if flag:
            purchase = Purchase(quantity=quantity, user=user, product=product)
            purchase.save()

            product.quantity -= quantity
            product.save()

            user.wallet -= product.price * quantity
            user.save()

            messages.success(self.request, 'Successful purchase')

        return HttpResponseRedirect(f"{self.success_url}?page={page_number}")

    def form_invalid(self, form):
        quantity = int(self.request.POST.get('quantity'))
        page_number = self.request.GET.get('page')

        if not quantity:
            messages.warning(self.request, "You need to select the quantity of the product")

        return HttpResponseRedirect(f"{self.success_url}?page={page_number}")


class ProductListView(ListView):
    template_name = 'product_list.html'
    model = Product
    ordering = ['price']
    paginate_by = 3


class ProductEditView(SuperuserRequiredMixin, UpdateView):
    template_name = 'product_edit.html'
    model = Product
    login_url = 'core:products'
    fields = ['name', 'description', 'price', 'quantity']

    def get_success_url(self):
        return reverse_lazy('core:products')


class PurchaseListView(LoginRequiredMixin, ListView):
    template_name = 'purchase_list.html'
    model = Purchase
    login_url = 'core:login'
    context_object_name = 'purchases'
    paginate_by = 10

    def get_queryset(self):
        ordering = self.request.GET.get('ordering', 'purchased_at')
        return Purchase.objects.filter(user=self.request.user)


class RefundsListView(SuperuserRequiredMixin, ListView):
    template_name = 'refund_list.html'
    model = Refund
    login_url = 'core:login'
    context_object_name = 'refunds'
    paginate_by = 3

    def get_queryset(self):
        return Refund.objects.get_queryset()


class PurchaseRefundView(LoginRequiredMixin, CreateView):
    login_url = 'login'
    form_class = RefundForm
    success_url = reverse_lazy('core:purchases')

    def form_valid(self, form):
        purchase_pk = self.request.POST.get('purchase_pk')
        purchase = Purchase.objects.get(id=purchase_pk)

        if len(Refund.objects.filter(purchase=purchase)):
            messages.error(self.request, "Refund already created")
        elif timezone.now() - purchase.purchased_at > timedelta(minutes=3):
            messages.error(self.request, "Time's up! You had a total of 3 minutes for the refund")
        else:
            refund = form.save(commit=False)
            refund.purchase = purchase
            refund.save()
            messages.success(self.request, "Your refund has been successfully initiated and is currently under review")
        return HttpResponseRedirect(self.success_url)


class RefundsAcceptView(SuperuserRequiredMixin, CreateView):
    login_url = 'login'
    model = Refund
    success_url = reverse_lazy('core:refunds')

    def post(self, request, *args, **kwargs):
        refund = self.get_object()
        purchase = refund.purchase
        product = purchase.product
        user = purchase.user

        product.quantity += purchase.quantity
        product.save()
        user.wallet += purchase.product.price * purchase.quantity
        user.save()

        purchase.delete()
        refund.delete()
        return HttpResponseRedirect(self.success_url)


class RefundsDeclineView(SuperuserRequiredMixin, DeleteView):
    login_url = 'login'
    model = Refund
    success_url = reverse_lazy('core:refunds')

    def post(self, request, *args, **kwargs):
        refund = self.get_object()
        refund.delete()
        return HttpResponseRedirect(self.success_url)

core/templates/base.html
<!DOCTYPE html>
{% load static %}

<html>

<head>
    <title> {% block title %}{% endblock %} </title>
    <link href="{% static 'css/main.css' %}?{% now 'U' %}" rel="stylesheet">
</head>

<body>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<header>
    <h1> Базар мимопроходцев </h1>
    {% include "navigation_bar.html" %}
</header>

{% block content %}
{% endblock %}

</body>

</html>

core/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block title %} Home {% endblock %}
{% block content %}
    <p> Welcome to Web Store{% if user.is_authenticated  %}, {{ user }}{% endif %}! </p>
{% endblock %}

core/templates/navigation_bar.html
{% block content %}

    <a href="{% url 'core:home' %}"> Home </a>
    <a href="{% url 'core:products' %}"> Products </a>

    {% if not request.user.is_authenticated %}
        <a href="{% url 'core:register' %}"> Register </a>
        <a href="{% url 'core:login' %}"> Login </a>
    {% endif %}

    {% if request.user.is_authenticated %}
        <a href="{% url 'core:purchases' %}"> Purchases </a>

        {% if request.user.is_superuser %}
            <a href="{% url 'core:product_add' %}"> Add product </a>
            <a href="{% url 'core:refunds' %}"> Refunds </a>
        {% endif %}

        <a href="{% url 'core:logout' %}"> Logout </a>
        Счёт: {{ request.user.wallet }} денег
    {% endif %}

{% endblock %}

core/templates/product_add.html
{% extends "base.html" %}
{% load static %}

{% block title %} Products {% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сотворить">
    </form>
{% endblock %}

core/templates/product_edit.html
{% extends "base.html" %}
{% load static %}

{% block title %} Products {% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Изменить">
    </form>
{% endblock %}

core/templates/product_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Products {% endblock %}
{% block content %}
    <h2> Список товаров: </h2>
    <ul>
        {% for product in object_list %}
            <li>
                <h3>{{ product.name }}</h3>
                <p> Цена: ${{ product.price }} | В наличии: {{ product.quantity }} </p>
                <p> Описание: {{ product.description }} </p>
                <form method="post" action="{% url 'core:product_purchase' %}?page={{ page_obj.number }}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="hidden" name="product_pk" value={{ product.pk }}>
                    {% if request.user.is_authenticated %}
                        <input type="number" name="quantity" value="1" min="0" max="999" step="1">
                        <input type="submit" name="action" value="Купить">
                    {% endif %}
                </form>
                {% if request.user.is_superuser %}
                    <a href="{% url 'core:product_edit' product.pk %}"> Изменить </a>
                {% endif %}
                <br>
            </li>
        {% endfor %}
    </ul>

    <div class="pagination">
    <span class="step-links">

        {% if page_obj.has_previous %}
            <a href="?page=1"> << </a>
            <a href="?page={{ page_obj.previous_page_number }}">| < |</a>
        {% endif %}

        стр. {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">| > |</a>
            <a href="?page={{ page_obj.paginator.num_pages }}"> >> </a>
        {% endif %}

    </span>
    </div>

{% endblock %}

core/templates/products_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Products {% endblock %}
{% block content %}
    <h2 font-size> Список товаров: </h2>
    <ul>
        {% for product in object_list %}
            <li>
                <h3>{{ product.name }}</h3>
                <p> Цена: ${{ product.price }} | В наличии: {{ product.quantity }} </p>
                <p> Описание: {{ product.description }} </p>
                <form method="post">
                    {% csrf_token %}

                    {% if request.user.is_authenticated %}
                        <input type="number" name="quantity" value="0" min="0" max="{{ product.quantity }}" step="1">
                        <input type="submit" value="Купить">
                        {% if request.user.is_superuser %}
                            <a href="{% url 'core:products_edit' %}"> Изменить </a>
                        {% endif %}
                    {% endif %}

                </form>
                <br>
            </li>
        {% endfor %}
    </ul>

    <div class="pagination">
    <span class="step-links">

        {% if page_obj.has_previous %}
            <a href="?page=1"> << </a>
            <a href="?page={{ page_obj.previous_page_number }}">| < |</a>
        {% endif %}

            стр. {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">| > |</a>
            <a href="?page={{ page_obj.paginator.num_pages }}"> >> </a>
        {% endif %}

    </span>
    </div>

{% endblock %}

core/templates/purchase_list.html
{% extends "base.html" %}
{% load static %}

{% block title %} Purchases {% endblock %}
{% block content %}
    <h2> Список покупок: </h2>
    <ul>
        {% for purchase in purchases %}
            <li>
                <h3>{{ product.name }}</h3>
                <form method="post" action="{% url 'core:purchase_refund' %}">
                    {% csrf_token %}
                    <input type="hidden" name="purchase_pk" value={{ purchase.pk }}>
                    {{ purchase.product.name }} - ${{ purchase.product.price }} x {{ purchase.quantity }} шт.
                    <button type="submit"> Возвратить</button>
                </form>
            </li>
        {% endfor %}
    </ul>

    <div class="pagination">
    <span class="step-links">

        {% if page_obj.has_previous %}
            <a href="?page=1"> << </a>
            <a href="?page={{ page_obj.previous_page_number }}">| < |</a>
        {% endif %}

        стр. {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">| > |</a>
            <a href="?page={{ page_obj.paginator.num_pages }}"> >> </a>
        {% endif %}

    </span>
    </div>
{% endblock %}

core/templates/purchases_list.html
{% extends "base.html" %}
{% load static %}

{% block title %} Purchases {% endblock %}
{% block content %}
    <p> Purchases list </p>
{% endblock %}

core/templates/refund_list.html
{% extends "base.html" %}
{% load static %}

{% block title %} Refunds {% endblock %}
{% block content %}
    <h2> Список возвратов: </h2>
    <ul>
        {% for refund in refunds %}
            <li>
                <h3>{{ refund }}</h3>

                <form method="post" action="{% url 'core:refunds_accept' refund.id %}">
                    {% csrf_token %}
                    <button type="submit"> Принять</button>
                </form>
                <br>
                <form method="post" action="{% url 'core:refunds_decline' refund.id %}">
                    {% csrf_token %}
                    <button type="submit"> Отклонить</button>
                </form>
            </li>
        {% endfor %}
    </ul>

    <div class="pagination">
    <span class="step-links">

        {% if page_obj.has_previous %}
            <a href="?page=1"> << </a>
            <a href="?page={{ page_obj.previous_page_number }}">| < |</a>
        {% endif %}

        стр. {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">| > |</a>
            <a href="?page={{ page_obj.paginator.num_pages }}"> >> </a>
        {% endif %}

    </span>
    </div>
{% endblock %}

core/templates/refunds_list.html
{% extends "base.html" %}
{% load static %}

{% block title %} Refunds {% endblock %}
{% block content %}
    <p> Refunds list </p>
{% endblock %}